name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: go vet ./...
      - run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      - run: go test ./...
      - run: go build -o /tmp/pitago ./src
